language: go
go:
  - 1.7
  - 1.8
  - 1.9
  - tip
env:
  global:
    - IGNORE_PATHS: example
script:
  - go test -v ./...
notifications:
  email:
    recipients:
      - apisupport@upwork.com
    on_failure: change
