language: go
go:
  - 1.12
  - 1.11
  - 1.10
  - tip
env:
  global:
    - IGNORE_PATHS: example
script:
  - go test -v ./...
notifications:
  email:
    recipients:
      - apisupport@upwork.com
    on_failure: change
